ONEUP-7670: fix job status report (#27)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -6,6 +6,9 @@ inputs:
   slack-webhook-url:
     description: 'Slack channel webhook URL to report to'
     required: true
+  parent-job-status:
+    description: 'parent job status'
+    required: true
   service-name:
     description: 'Explicit service name in case the repository does not represent a single service (monorepo)'
     required: false
@@ -23,6 +26,12 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Setup - Validate Inputs
+      shell: bash
+      run: |
+        [[ "${{ inputs.slack-webhook-url }}" ]] || { echo "input 'slack-webhook-url' cannot be blank"; exit 1; }
+        [[ "${{ inputs.parent-job-status }}" ]] || { echo "input 'parent-job-status' cannot be blank"; exit 1; }
+
     - if: always() && (github.ref == 'refs/heads/master' || inputs.always-notify == 'true')
       shell: bash
       run: |
@@ -58,7 +67,7 @@ runs:
         echo "FAILURE_MESSAGE=$FAILURE_MESSAGE" >> $GITHUB_ENV
 
     - name: Report - success [on master]
-      if: job.status == 'success' && (github.ref == 'refs/heads/master' || inputs.always-notify == 'true')
+      if:  inputs.parent-job-status == 'success' && (github.ref == 'refs/heads/master' || inputs.always-notify == 'true')
       uses: slackapi/slack-github-action@v1
       env:
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
@@ -79,7 +88,7 @@ runs:
           }
 
     - name: Report - failure [on master]
-      if: job.status == 'failure' && (github.ref == 'refs/heads/master' || inputs.always-notify == 'true')
+      if: inputs.parent-job-status == 'failure' && (github.ref == 'refs/heads/master' || inputs.always-notify == 'true')
       uses: slackapi/slack-github-action@v1
       env:
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
